export const searchList = [
  // Delta Green Sections
  { chapter: "Delta Green", section: "Overview" },
  { chapter: "Delta Green", section: "The World of Delta Green" },
  {
    chapter: "Delta Green",
    section: "What Is Delta Green?",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
  },
  {
    chapter: "Delta Green",
    section: "How the Game is Played",
  },
  {
    chapter: "Delta Green",
    section: "How to Play an Agent",
  },

  // Delta Green Headers
  {
    chapter: "Delta Green",
    section: "The World of Delta Green",
    header: "The Unnatural in the Modern Era",
  },
  {
    chapter: "Delta Green",
    section: "What Is Delta Green?",
    header: "Potential Recruits",
  },
  {
    chapter: "Delta Green",
    section: "What Is Delta Green?",
    header: "Operational Briefing",
  },
  {
    chapter: "Delta Green",
    section: "What Is Delta Green?",
    header: "On the Ground",
  },
  {
    chapter: "Delta Green",
    section: "What Is Delta Green?",
    header: "Retirement",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Investigation and Uncertainty",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Suspense and Horror",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Violence and Moral Choices",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Sanity and Comprehension",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Keeping Secrets",
  },
  {
    chapter: "Delta Green",
    section: "The Fundamentals",
    header: "Personal and Professional Consequences",
  },
  {
    chapter: "Delta Green",
    section: "How the Game is Played",
    header: "Your Agent In the Game",
  },
  {
    chapter: "Delta Green",
    section: "How the Game is Played",
    header: "The Handler",
  },

  // Rules Sections
  { chapter: "Rules", section: "How to Play" },
  { chapter: "Rules", section: "Combat" },
  { chapter: "Rules", section: "Sanity" },
  { chapter: "Rules", section: "Home" },

  // Rules Headers
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
    subheader: "Resolving a Test Without Dice",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
    subheader: "Resolving a Test With Dice",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
    subheader: "Using a Stat",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
    subheader: "Bonuses & Penalties",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Using Skills",
    subheader: "Group Rolls",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Success and Failure",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Success and Failure",
    subheader: "Critical Success",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Success and Failure",
    subheader: "Success",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Success and Failure",
    subheader: "Failure",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Success and Failure",
    subheader: "Fumble",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "The Luck Roll",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Time Required",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Opposed Tests",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Pursuit",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Willpower Points",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Willpower Points",
    subheader: "Exhaustion",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Willpower Points",
    subheader: "Sleeplessness",
  },
  {
    chapter: "Rules",
    section: "How to Play",
    header: "Willpower Points",
    subheader: "Sleeplessness",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Aim",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Attack",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Called Shot",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Disarm",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Dodge",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Escape",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Fight Back",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Move",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Pin",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Wait",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "The Turn",
    subheader: "Anything Else",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Attack Rolls",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Attack Rolls",
    subheader: "Surprise Attacks",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Attack Rolls",
    subheader: "Shooting into a Crowd",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Defense Rolls",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Defense Rolls",
    subheader: "Dodging and Fighting Back",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Defense Rolls",
    subheader: "Dodging Ranged Attacks",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Defense Rolls",
    subheader: "Defending After Attacking",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Damage",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Damage",
    subheader: "Healing",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Damage",
    subheader: "Complications",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Damage",
    subheader: "Recovering Stat Points",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Lethality Rating",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Lethality Rating",
    subheader: "Kill Radius",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Lethality Rating",
    subheader: "Suppression",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Lethality Rating",
    subheader: "Selective Fire",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Lethality Rating",
    subheader: "Blowing Things Up",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Fragile",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Exposed",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Armored",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Huge",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Transcendant",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Protection in Combat",
    subheader: "Armor Piercing Weapons",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Poison and Disease",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Falling",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Impact",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Suffocation",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Fire",
  },
  {
    chapter: "Rules",
    section: "Combat",
    header: "Other Threats",
    subheader: "Cold",
  },
  {
    chapter: "Rules",
    section: "Sanity",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Rules of Thumb for SAN Loss",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Threats to SAN",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Threats to SAN",
    subheader: "Violence",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Threats to SAN",
    subheader: "Helplessness",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Threats to SAN",
    subheader: "The Unnatural",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Insanity and Disorders",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Temporary Insanity",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Temporary Insanity",
    subheader: "Flee",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Temporary Insanity",
    subheader: "Struggle",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Temporary Insanity",
    subheader: "Submit",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Disorders",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Disorders",
    subheader: "Acute Episodes",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Disorders",
    subheader: "Acute Episodes",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Permanent Insanity",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Resisting Insanity",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Resisting Insanity",
    subheader: "Adapting to Sanity Loss",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Resisting Insanity",
    subheader: "Projecting Onto a Bond",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Resisting Insanity",
    subheader: "Repressing Insanity",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Recovery",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Recovery",
    subheader: "Therapy or Home Life",
  },
  {
    chapter: "Rules",
    section: "Sanity",
    header: "Recovery",
    subheader: "Destroying the Unnatural",
  },
  {
    chapter: "Rules",
    section: "Home",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "What Changed",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Fulfill Responsibilities",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Back to Nature",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Establish a New Bond",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Go to Therapy",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Improve Skills or Stats",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Personal Motivation",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Special Training",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Stay On the Case",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Personal Pursuits",
    subheader: "Study the Unnatural",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Getting Fired",
  },
  {
    chapter: "Rules",
    section: "Home",
    header: "Prosecution",
  },
  {
    chapter: "Equipment and Services",
    section: "Official Requisition",
  },
  {
    chapter: "Equipment and Services",
    section: "Spending Your Own Money",
  },
  {
    chapter: "Equipment and Services",
    section: "Spending Your Own Money",
    header: "Limitations",
  },
  {
    chapter: "Equipment and Services",
    section: "Using Illicit Money",
  },
  {
    chapter: "Equipment and Services",
    section: "Restricted Items",
  },
  {
    chapter: "Equipment and Services",
    section: "Restricted Items",
    header: "The Black Market",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Concealment",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Bright Lights",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Hand-to-Hand Weapons",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Tear Gas and Pepper Spray",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Stun Grenades",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Electroshock Weapons",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Firearms",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Firearms",
    subheader: "Pistols",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Firearms",
    subheader: "Shotguns",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Firearms",
    subheader: "Submachine Guns",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Firearms",
    subheader: "Rifles and Carbines",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Heavy Weapons",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Demolitions",
  },
  {
    chapter: "Equipment and Services",
    section: "Weapons",
    header: "Artillery",
  },
  {
    chapter: "Equipment and Services",
    section: "Body Armor",
  },
  {
    chapter: "Equipment and Services",
    section: "Vehicles",
  },
  {
    chapter: "Equipment and Services",
    section: "Vehicles",
    subheading: "Ramming",
  },
  {
    chapter: "Equipment and Services",
    section: "Vehicles",
    header: "Ground Vehicles",
  },
  {
    chapter: "Equipment and Services",
    section: "Vehicles",
    header: "Water Vehicles",
  },
  {
    chapter: "Equipment and Services",
    section: "Vehicles",
    header: "Air Vehicles",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Transportation",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Lodgings",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Covers and Legends",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Storage",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Restraints",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Research",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Communications and Computers",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Surveillance",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Lighting and Vision",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Breaking and Entering",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Emergency and Survival",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Off-the-books Medical Care",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Weapon Accessories",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Law Enforcement (Official Requisition Only)",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Military (Official Requisition Only)",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Intelligence (Official Requisition Only)",
  },
  {
    chapter: "Equipment and Services",
    section: "Gear and Services",
    header: "Public Safety (Official Requisition Only)",
  },
  {
    chapter: "Training",
    section: "Introduction",
  },
  {
    chapter: "Training",
    section: "Introduction",
    header: "The Role-Playing",
  },
  {
    chapter: "Training",
    section: "Introduction",
    header: "Ready to Play",
  },
  {
    chapter: "Training",
    section: "Basics",
  },
  {
    chapter: "Training",
    section: "Basics",
    header: "Does it Require a Stat or a Skill",
  },
  {
    chapter: "Training",
    section: "Basics",
    header: "Does it Require a Roll",
  },
  {
    chapter: "Training",
    section: "Basics",
    header: "Roll Results",
  },
  {
    chapter: "Training",
    section: "Basics",
    header: "Other Types of Rolls",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Combat",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Combat",
    subheader: "Damage and Death",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
    subheader: "Insanity",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
    subheader: "Reducing Sanity Loss",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
    subheader: "Adapting to Sanity Loss",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
    subheader: "Repressing Symptoms of Insanity",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Sanity",
    subheader: "Regaining Sanity Points",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Willpower",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Willpower",
    subheader: "Low Willpower",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Willpower",
    subheader: "Regaining Willpower",
  },
  {
    chapter: "Training",
    section: "Combat, Sanity, and Willpower",
    header: "Willpower",
    subheader: "Exhaustion",
  },
  {
    chapter: "Training",
    section: "Being an Agent",
  },
  {
    chapter: "Training",
    section: "Being an Agent",
    header: "Creating an Agent",
  },
  {
    chapter: "Training",
    section: "Being an Agent",
    header: "Agent Etiquette",
  },
  {
    chapter: "Training",
    section: "After the Operation",
  },
  {
    chapter: "Training",
    section: "After the Operation",
    header: "Rolling Failures",
  },
  {
    chapter: "Training",
    section: "After the Operation",
    header: "Home",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Statistics",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Statistic Definitions",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Attributes",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Attribute Definitions",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Base Rating",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "How Skills Work",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Common Knowledge",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Using Libraries",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Improving Skills",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Special Training",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skills",
    subheader: "Skill (Types)",
  },
  {
    chapter: "Professions",
    section: "Stats and Skills",
    header: "Skill Definitions",
  },
  {
    chapter: "Professions",
    section: "Profession List",
  },
  {
    chapter: "Professions",
    section: "Bonus Skill Package List",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Going Unnoticed",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Surveillance",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Pursuit",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Breaking & Entering",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Search & Arrest",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Interrogation",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Human Assets",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Medical Treatment",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Evidence-Tampering",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Medical Treatment",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Disposing of a Body",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Communications",
  },
  {
    chapter: "Tradecraft",
    section: "",
    header: "Safe Houses and Green Boxes",
  },
];
