export interface IUserAgent {
  name: string;
  profession: string;
  personalDetails: {
    employer: string;
    nationality: string;
    age: number;
    sex: string;
    occupationalHistory: string;
    personality: string;
    motivations: string;
  };
  stats: {
    strength: number;
    constitution: number;
    dexterity: number;
    intelligence: number;
    power: number;
    charisma: number;
  };
  attributes: { hitPoints: any; willpowerPoints: any; sanity: any };
  skills: {
    accounting: number;
    alertness: number;
    anthropology: number;
    archeology: number;
    art: { label: string; skill: number }[];
    artillery: number;
    athletics: number;
    bureaucracy: number;
    computerScience: number;
    craft: { label: string; skill: number }[];
    criminology: number;
    demolitions: number;
    disguise: number;
    dodge: number;
    drive: number;
    firearms: number;
    firstAid: number;
    foreignLanguage: { label: string; skill: number }[];
    forensics: number;
    heavyMachinery: number;
    heavyWeapons: number;
    history: number;
    humint: number;
    law: number;
    medicine: number;
    meleeWeapons: number;
    militaryScience: { label: string; skill: number }[];
    navigate: number;
    occult: number;
    persuade: number;
    pharmacy: number;
    pilot: { label: string; skill: number }[];
    psychotherapy: number;
    ride: number;
    science: { label: string; skill: number }[];
    search: number;
    signint: number;
    stealth: number;
    surgery: number;
    survival: number;
    swim: number;
    unarmedCombat: number;
    unnatural: number;
  };
  additionalSkills: any[];
  bonds: any[];
}
